- API/SSO/package-lock.json
- API/SSO/package.json
- API/SSO/src/index.html
- API/SSO/src/main.js
- API/SSO/src/routes.js
- SITE/Login/package-lock.json
- SITE/Login/package.json
- SITE/Login/src/App.jsx
- SITE/Login/src/components/Button.jsx
- SITE/Login/src/setupProxy.js
- package.json
Configuration for Dev deployment.
> SSO API Configuration Setup

- SITE/smartgroup/package-lock.json
- SITE/smartgroup/package.json
- SITE/smartgroup/src/App.jsx
- SITE/smartgroup/src/components/CancelButton.jsx
- SITE/smartgroup/src/components/CreateButton.jsx
- SITE/smartgroup/src/components/InputBox.jsx
- SITE/smartgroup/src/components/Nav.jsx
- SITE/smartgroup/src/pages/CreateRoom.jsx
- package-lock.json
- package.json
Adding the Create Room Page to the app and nav component, using the router. App.jsx was slightly modified to import the page. All else is new additions.
For now, we are continuing to use styled-components. Next Sprint we will decide on a single formatting style for CSS.
> Add Create Room Page to Nav component and router.

- API/SSO/package-lock.json
- API/SSO/package.json
- API/SSO/src/config.js
- API/SSO/src/main.js
- API/SSO/src/queries.js
- API/SSO/src/routes.js
- package.json
SSO API now has working registration route able to query dev db
> Registration Route working

- SITE/smartgroup/src/App.jsx
- SITE/smartgroup/src/GlobalStyles.css.js
- SITE/smartgroup/src/components/Nav.jsx
- SITE/smartgroup/src/pages/Dashboard.jsx
- SITE/smartgroup/src/pages/ProfilePage.jsx
added page for student's personal info: name, school, id, classes
> Profile Page Added

- SITE/smartgroup/package-lock.json
- SITE/smartgroup/package.json
- SITE/smartgroup/src/App.jsx
- SITE/smartgroup/src/components/Nav.jsx
- SITE/smartgroup/src/pages/StudyRoom.jsx
Implements the react-chat-engine module on a new page with a placeholder study room and account.
> Study room page

- SITE/smartgroup/src/components/CancelButton.jsx
- SITE/smartgroup/src/components/CreateButton.jsx
- SITE/smartgroup/src/pages/StudyGroupsList.jsx
Buttons on each page now route approximately to where they will go in the final build. Buttons do not currently pass through any other information, they just route to other pages.
> Adds routing functionality to previous buttons

- API/SSO/src/main.js
- API/SSO/src/queries.js
- API/SSO/src/routes.js
- SITE/Login/src/App.jsx
- SITE/Login/src/components/InputBox.jsx
- SITE/Login/src/components/LoginForm.jsx
- SITE/Login/src/components/RegisterForm.jsx
- SITE/Login/src/config.js
- package-lock.json
- package.json
Register and Login requests now called from Login page. Cursory Session management setup.
> Security API Frontend Hookup

- API/Main/src/routes/index.js
- SITE/smartgroup/src/App.jsx
- SITE/smartgroup/src/pages/Dashboard.jsx
- SITE/smartgroup/src/pages/ProfilePage.jsx
- SITE/smartgroup/src/pages/StudyGroupsList.jsx
Partial completion of component rebuild.
> Component rebuild

- API/SSO/src/main.js
- API/SSO/src/queries.js
- API/SSO/src/routes.js
- SITE/smartgroup/src/components/Nav.jsx
Logout Functionality and Replacing student-id with a random UUID.
> Auth logout

- SITE/smartgroup/src/pages/StudyRoom.css
Changes background colors and borders of chat room module to look like rest of the app.
> Finalize basic CSS changes (border and background)

- API/Main/src/db/index.js
- API/Main/src/routes/index.js
- API/Main/src/server.js
- SITE/smartgroup/src/App.jsx
- SITE/smartgroup/src/pages/Dashboard.jsx
- SITE/smartgroup/src/pages/ProfilePage.jsx
- SITE/smartgroup/src/pages/StudyGroupsList.jsx
Components rebuilt to accept data from props and display them appropriately. Front end now makes API calls to Main API and sends data to correct components to be dispalyed
> Component Rebuild and Front End API Hookup

- .gitignore
- API/Auth/src/routes.js
- API/Main/src/config.js
- API/Main/src/db/index.js
- SITE/Login/src/config.js
- SITE/smartgroup/src/components/Nav.jsx
- package-lock.json
- package.json
- webpack.config.cjs
environment variable configuration completed for staging of production pipeline, and moving database to cloud.
> Config of env variables

- API/Auth/src/config.js
- API/Auth/src/mailer.js
- API/Auth/src/main.js
- API/Auth/src/queries.js
- SITE/smartgroup/src/pages/StudyRoom.jsx
The account link to the chat module has been fully implemented on registration. There is, however, a slight bug when doing the email confirmation on Gmail: it currently displays as a blank page. The app does not crash however and all other features work normally.
> Chat Acc. Link Added (Gmail confirm is bugged)

- SITE/smartgroup/src/pages/Dashboard.jsx
Added recommended studygroups to dashboard
> Recommended studygroups

- API/Main/src/db/index.js
- API/Main/src/routes/index.js
added route/query to update student's preferred name
> Main api preferred name

- API/Main/src/db/index.js
- API/Main/src/routes/index.js
Created route and queries for inserting new studygroup into database, 
also creates new rows in Studygroup_Has_Course and Studygroup_Has_Student with appropriate data.
> Main api create studygroup

- SITE/smartgroup/src/App.jsx
- SITE/smartgroup/src/components/Button.jsx
- SITE/smartgroup/src/components/CancelButton.jsx
- SITE/smartgroup/src/components/CreateButton.jsx
- SITE/smartgroup/src/pages/CreateRoom.jsx
- SITE/smartgroup/src/singleton.js
Create room page now creates a chat room and puts a new room in database.
There is currently no validation, and the create room button does not link you to the chat room page.
I've noticed that the Study Group List page is displaying white, but I'm not sure if that's because of something on my end or the adjustments we've been making to the Study Group List. Can someone check that for me?
> Create room class rebase rebase

- API/Main/src/db/index.js
- SITE/smartgroup/src/App.jsx
- SITE/smartgroup/src/pages/CreateRoom.jsx
There is now a chat bot that sets up all chat rooms when study groups are created. The chat bot automatically adds the user that "created" the chat room when it is created.
This was all moved from CreateRoom and crammed into the previously made createstudygroup route.
> Chat bot now sets up all chat rooms when creating

- API/Main/src/db/index.js
- SITE/smartgroup/src/pages/CreateRoom.jsx
- SITE/smartgroup/src/pages/StudyGroupsList.jsx
study group should display:
Studygroup ID,
Course,
Location,
Material,
Number of people in studygroup,
Timeframe
> Fixed studygroup list page to display correct info

- SITE/smartgroup/src/App.jsx
- SITE/smartgroup/src/pages/ProfilePage.jsx
Profile Page Course List Shows:
Course, 
Instructor
> Profile page class list change

- API/Main/src/db/index.js
- API/Main/src/routes/index.js
- SITE/smartgroup/src/App.jsx
- SITE/smartgroup/src/pages/Dashboard.jsx
- SITE/smartgroup/src/pages/StudyGroupsList.css
Shows study groups that are for courses that the student has added to their account
> Added fucntionality to recommended study groups on dashboard

- API/Main/src/db/index.js
- API/Main/src/routes/index.js
- SITE/smartgroup/src/App.jsx
- SITE/smartgroup/src/components/RowElement.jsx
- SITE/smartgroup/src/pages/CreateRoom.jsx
- SITE/smartgroup/src/pages/StudyGroupsList.jsx
Clicking row entry in study group list adds you to the studygroup in the database and the chatroom using a new route
(Now without GitHub's merge mistakes)
> Join studygroup rebase
